# Generated by Django 5.2.1 on 2025-05-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=200, verbose_name='Nome do Curso')),
                ('duracao_meses', models.IntegerField(verbose_name='Duração (meses)')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária (horas)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor (R$)')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
