# Generated by Django 5.2.1 on 2025-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Senac', '0002_mensagemcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem_curso',
            field=models.ImageField(blank=True, null=True, upload_to='cursos_imagens/', verbose_name='Imagem do Curso'),
        ),
    ]
